// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekhaneCoreApi.Data;

namespace YemekhaneCoreApi.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("YemekhaneCoreApi.Entities.FoodPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Food5")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
